# Generated by Django 3.1.4 on 2020-12-22 07:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201221_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
