# Generated by Django 3.1.4 on 2020-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateTimeField(null=True),
        ),
    ]
