# Generated by Django 3.1.4 on 2020-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0002_subscription_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
