# Generated by Django 3.1.4 on 2020-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0003_subscription_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
