# Generated by Django 3.1.4 on 2020-12-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0007_exercisesplan_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesplan',
            name='how_it_works',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
