# Generated by Django 3.1.4 on 2020-12-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0009_auto_20201229_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_1',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_4',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_5',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_6',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='description_7',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
