# Generated by Django 3.1.4 on 2020-12-31 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription_plans', '0010_auto_20201229_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesplan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisesplan',
            name='has_access',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptions'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
