# Generated by Django 3.1.4 on 2020-12-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0011_auto_20201231_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesplan',
            name='has_access',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptions'),
        ),
    ]
