# Generated by Django 3.1.4 on 2021-01-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0012_auto_20201231_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesplan',
            name='has_access',
        ),
    ]
